SELECT MP.MEMBER_ID, MP.MEMBER_NAME, MP.GENDER, DATE_FORMAT(MP.DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE AS MP
WHERE MONTH(MP.DATE_OF_BIRTH) = 3
    AND MP.GENDER = 'W'
    AND MP.TLNO IS NOT NULL
ORDER BY MP.MEMBER_ID ASC;